USE cyklo;

ALTER TABLE bikes
    ADD COLUMN IF NOT EXISTS tires VARCHAR(120) DEFAULT NULL AFTER weight_kg,
    ADD COLUMN IF NOT EXISTS lighting VARCHAR(120) DEFAULT NULL AFTER tires,
    ADD COLUMN IF NOT EXISTS front_hub VARCHAR(120) DEFAULT NULL AFTER bottom_bracket,
    ADD COLUMN IF NOT EXISTS rear_hub VARCHAR(120) DEFAULT NULL AFTER front_hub,
    ADD COLUMN IF NOT EXISTS front_rotor VARCHAR(120) DEFAULT NULL AFTER rear_hub,
    ADD COLUMN IF NOT EXISTS rear_rotor VARCHAR(120) DEFAULT NULL AFTER front_rotor,
    ADD COLUMN IF NOT EXISTS saddle VARCHAR(120) DEFAULT NULL AFTER display_name,
    ADD COLUMN IF NOT EXISTS cassette VARCHAR(120) DEFAULT NULL AFTER saddle,
    ADD COLUMN IF NOT EXISTS frame_spec VARCHAR(120) DEFAULT NULL AFTER cassette,
    ADD COLUMN IF NOT EXISTS fork_spec VARCHAR(120) DEFAULT NULL AFTER frame_spec,
    ADD COLUMN IF NOT EXISTS chain_spec VARCHAR(120) DEFAULT NULL AFTER fork_spec;
