USE cyklo;

ALTER TABLE bikes
    ADD COLUMN IF NOT EXISTS manufacturer VARCHAR(120) DEFAULT NULL AFTER category,
    ADD COLUMN IF NOT EXISTS color VARCHAR(60) DEFAULT NULL AFTER image_url,
    ADD COLUMN IF NOT EXISTS frame_size VARCHAR(60) DEFAULT NULL AFTER color,
    ADD COLUMN IF NOT EXISTS wheel_size VARCHAR(60) DEFAULT NULL AFTER frame_size,
    ADD COLUMN IF NOT EXISTS weight_kg DECIMAL(5,2) DEFAULT NULL AFTER wheel_size,
    ADD COLUMN IF NOT EXISTS brakes VARCHAR(120) DEFAULT NULL AFTER weight_kg,
    ADD COLUMN IF NOT EXISTS bottom_bracket VARCHAR(120) DEFAULT NULL AFTER brakes,
    ADD COLUMN IF NOT EXISTS front_derailleur VARCHAR(120) DEFAULT NULL AFTER bottom_bracket,
    ADD COLUMN IF NOT EXISTS rear_derailleur VARCHAR(120) DEFAULT NULL AFTER front_derailleur,
    ADD COLUMN IF NOT EXISTS wheels VARCHAR(120) DEFAULT NULL AFTER rear_derailleur,
    ADD COLUMN IF NOT EXISTS battery VARCHAR(120) DEFAULT NULL AFTER wheels,
    ADD COLUMN IF NOT EXISTS motor VARCHAR(120) DEFAULT NULL AFTER battery,
    ADD COLUMN IF NOT EXISTS display_name VARCHAR(120) DEFAULT NULL AFTER motor,
    ADD COLUMN IF NOT EXISTS note VARCHAR(255) DEFAULT NULL AFTER display_name;
